"""empty message

Revision ID: 068164f80753
Revises: 7c50d1c439ef
Create Date: 2020-06-24 20:40:11.652656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068164f80753'
down_revision = '7c50d1c439ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
