"""empty message

Revision ID: 11597d15f387
Revises: 8a17cfc7f057
Create Date: 2020-06-05 16:41:41.039654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11597d15f387'
down_revision = '8a17cfc7f057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
