"""empty message

Revision ID: 3a524af595dc
Revises: 05f2a612a56f
Create Date: 2020-08-22 17:29:24.012887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a524af595dc'
down_revision = '05f2a612a56f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_changes', sa.Column('password_changed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_changes', 'password_changed')
    # ### end Alembic commands ###
