"""empty message

Revision ID: 3c64289c3517
Revises: a8f6fd5a6763
Create Date: 2020-08-20 10:48:18.636373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c64289c3517'
down_revision = 'a8f6fd5a6763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_organizers_rel')
    op.drop_index('ix_event_organizers_name', table_name='event_organizers')
    op.drop_table('event_organizers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_organizers',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('website_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='event_organizers_user_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='event_organizers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_event_organizers_name', 'event_organizers', ['name'], unique=False)
    op.create_table('event_organizers_rel',
    sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('organizer_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='event_organizers_rel_event_id_fkey'),
    sa.ForeignKeyConstraint(['organizer_id'], ['event_organizers.id'], name='event_organizers_rel_organizer_id_fkey')
    )
    # ### end Alembic commands ###
