"""empty message

Revision ID: 48265e18b4ac
Revises: 9f39be674fed
Create Date: 2020-08-20 10:55:35.315485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48265e18b4ac'
down_revision = '9f39be674fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
