"""empty message

Revision ID: 7c50d1c439ef
Revises: 1f1fa5ff23e4
Create Date: 2020-06-19 17:00:56.630859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c50d1c439ef'
down_revision = '1f1fa5ff23e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
