"""empty message

Revision ID: 93b8b37ed10a
Revises: 2491895b43dc
Create Date: 2020-02-08 14:00:43.413681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b8b37ed10a'
down_revision = '2491895b43dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_categories', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brand_categories', 'slug')
    # ### end Alembic commands ###
