"""empty message

Revision ID: 9d33c7394288
Revises: ef1f94d6a646
Create Date: 2020-08-20 10:53:37.043886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d33c7394288'
down_revision = 'ef1f94d6a646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_organizers_rel',
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('organizer_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['event_organizers.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_organizers_rel')
    # ### end Alembic commands ###
