"""empty message

Revision ID: 9f39be674fed
Revises: 9d33c7394288
Create Date: 2020-08-20 10:54:45.309429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f39be674fed'
down_revision = '9d33c7394288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
