"""empty message

Revision ID: a8f6fd5a6763
Revises: 068164f80753
Create Date: 2020-08-20 10:15:22.973504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f6fd5a6763'
down_revision = '068164f80753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_organizers_rel',
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('organizer_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['event_organizers.id'], )
    )
    op.add_column('event_organizers', sa.Column('image', sa.String(), nullable=True))
    op.add_column('event_organizers', sa.Column('name', sa.String(), nullable=True))
    op.add_column('event_organizers', sa.Column('website_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_event_organizers_name'), 'event_organizers', ['name'], unique=False)
    op.drop_constraint('event_organizers_event_id_fkey', 'event_organizers', type_='foreignkey')
    op.drop_column('event_organizers', 'event_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_organizers', sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('event_organizers_event_id_fkey', 'event_organizers', 'events', ['event_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_event_organizers_name'), table_name='event_organizers')
    op.drop_column('event_organizers', 'website_url')
    op.drop_column('event_organizers', 'name')
    op.drop_column('event_organizers', 'image')
    op.drop_table('event_organizers_rel')
    # ### end Alembic commands ###
