"""empty message

Revision ID: caac35060cb9
Revises: 11597d15f387
Create Date: 2020-06-12 16:16:18.856725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caac35060cb9'
down_revision = '11597d15f387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_online', sa.String(), nullable=True))
    op.create_index(op.f('ix_events_is_online'), 'events', ['is_online'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_is_online'), table_name='events')
    op.drop_column('events', 'is_online')
    # ### end Alembic commands ###
