"""empty message

Revision ID: f69a2078f7bf
Revises: 48265e18b4ac
Create Date: 2020-08-20 11:01:49.259946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69a2078f7bf'
down_revision = '48265e18b4ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
