"""empty message

Revision ID: fe40996ff5e6
Revises: c6d16a175b84
Create Date: 2020-02-08 13:57:22.359038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe40996ff5e6'
down_revision = 'c6d16a175b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_categories', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('event_categories', 'updated_at')
    op.drop_column('event_categories', 'creatd_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_categories', sa.Column('creatd_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('event_categories', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('event_categories', 'created_at')
    # ### end Alembic commands ###
