"""update event media table

Revision ID: 042f01b0898b
Revises: 9059bc9d224f
Create Date: 2019-05-31 08:47:07.010247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042f01b0898b'
down_revision = '9059bc9d224f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_media', sa.Column('filename', sa.String(), nullable=True))
    op.drop_column('event_media', 'is_cover_image')
    op.drop_column('event_media', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_media', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_media', sa.Column('is_cover_image', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('event_media', 'filename')
    # ### end Alembic commands ###
