"""add reservation_lines table

Revision ID: 062c67821f70
Revises: 26ad363cbda9
Create Date: 2019-03-22 16:53:25.319004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062c67821f70'
down_revision = '26ad363cbda9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_reservation_lines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_type_id', sa.String(), nullable=True),
    sa.Column('ticket_qty', sa.Integer(), nullable=True),
    sa.Column('reservation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['ticket_reservations.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['event_ticket_types.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_reservation_lines_ticket_type_id'), 'ticket_reservation_lines', ['ticket_type_id'], unique=False)
    op.drop_index('ix_ticket_reservations_ticket_type_id', table_name='ticket_reservations')
    op.drop_constraint('ticket_reservations_ticket_type_id_fkey', 'ticket_reservations', type_='foreignkey')
    op.drop_column('ticket_reservations', 'ticket_qty')
    op.drop_column('ticket_reservations', 'ticket_type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_reservations', sa.Column('ticket_type_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ticket_reservations', sa.Column('ticket_qty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('ticket_reservations_ticket_type_id_fkey', 'ticket_reservations', 'event_ticket_types', ['ticket_type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_ticket_reservations_ticket_type_id', 'ticket_reservations', ['ticket_type_id'], unique=False)
    op.drop_index(op.f('ix_ticket_reservation_lines_ticket_type_id'), table_name='ticket_reservation_lines')
    op.drop_table('ticket_reservation_lines')
    # ### end Alembic commands ###
