"""update event_tickets

Revision ID: 07cb96c90f4c
Revises: e76e2ed3f162
Create Date: 2019-03-26 20:26:42.423769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07cb96c90f4c'
down_revision = 'e76e2ed3f162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_tickets', sa.Column('my_assignment', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_tickets', 'my_assignment')
    # ### end Alembic commands ###
