"""update users table

Revision ID: 0d63c609ce6a
Revises: 78bb32d9fb63
Create Date: 2019-01-11 15:42:08.456073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d63c609ce6a'
down_revision = '78bb32d9fb63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
