"""update users

Revision ID: 0da5ff49b9d8
Revises: 5e90242c6ddf
Create Date: 2019-01-10 20:06:02.634853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da5ff49b9d8'
down_revision = '5e90242c6ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_payment_details_default_payment_type', table_name='user_payment_details')
    op.drop_column('user_payment_details', 'default_payment_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_payment_details', sa.Column('default_payment_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_user_payment_details_default_payment_type', 'user_payment_details', ['default_payment_type'], unique=False)
    # ### end Alembic commands ###
