"""update user payment details table

Revision ID: 0fcde15db3ab
Revises: a727f8e9e68c
Create Date: 2019-05-18 20:38:06.706005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fcde15db3ab'
down_revision = 'a727f8e9e68c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
