"""update again

Revision ID: 14ec7f67cb83
Revises: 483f6066a4e6
Create Date: 2019-03-26 08:39:51.831207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ec7f67cb83'
down_revision = '483f6066a4e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
