"""update EventTicketType

Revision ID: 17159eabe5bb
Revises: 9494429cb673
Create Date: 2019-03-18 21:41:23.654307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17159eabe5bb'
down_revision = '9494429cb673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_attendees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('attendee_id', sa.String(), nullable=True),
    sa.Column('sale_line_id', sa.String(), nullable=True),
    sa.Column('ownership_by_purchase', sa.Boolean(), nullable=True),
    sa.Column('ownership_by_assignment', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['attendee_id'], ['users.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['sale_line_id'], ['ticket_sale_lines.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('event_ticket_types', sa.Column('remaining_qty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_ticket_types', 'remaining_qty')
    op.drop_table('event_attendees')
    # ### end Alembic commands ###
