"""update users table

Revision ID: 17b6718c03f5
Revises: b16831cebfb1
Create Date: 2019-01-11 21:05:09.464907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b6718c03f5'
down_revision = 'b16831cebfb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('calling_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('country_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'countries', ['country_id'], ['id'])
    op.drop_column('users', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'country_id')
    op.drop_table('countries')
    # ### end Alembic commands ###
