"""update followers table

Revision ID: 17bfddb4bdc5
Revises: 23c15e6375b7
Create Date: 2019-01-04 09:33:42.225779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17bfddb4bdc5'
down_revision = '23c15e6375b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_followers', sa.Column('follower_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'user_followers', 'users', ['follower_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_followers', type_='foreignkey')
    op.drop_column('user_followers', 'follower_id')
    # ### end Alembic commands ###
