"""update sale order table

Revision ID: 1a3b59ce4473
Revises: fbc7ddac1512
Create Date: 2019-05-28 17:02:24.669115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3b59ce4473'
down_revision = 'fbc7ddac1512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
