"""udpate app_notifications

Revision ID: 1adbcdb8037a
Revises: 3e3681652db6
Create Date: 2019-03-29 22:45:42.256122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1adbcdb8037a'
down_revision = '3e3681652db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
