"""update users table

Revision ID: 1b7e7e20317c
Revises: 9d63e411100e
Create Date: 2018-12-29 20:51:16.853139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7e7e20317c'
down_revision = '9d63e411100e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_ghost', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_ghost')
    # ### end Alembic commands ###
