"""update sale order lines table

Revision ID: 222acbfdd099
Revises: e09c1a6f856e
Create Date: 2019-05-28 15:36:16.200993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222acbfdd099'
down_revision = 'e09c1a6f856e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_sale_lines', sa.Column('net_amount', sa.Float(), nullable=True))
    op.add_column('ticket_sale_lines_discounts', sa.Column('order_line_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'ticket_sale_lines_discounts', 'ticket_sale_lines', ['order_line_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_sale_lines_discounts', type_='foreignkey')
    op.drop_column('ticket_sale_lines_discounts', 'order_line_id')
    op.drop_column('ticket_sale_lines', 'net_amount')
    # ### end Alembic commands ###
