"""udpate tables

Revision ID: 222def23286a
Revises: f6b4f93de9aa
Create Date: 2019-03-25 14:11:24.027232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222def23286a'
down_revision = 'f6b4f93de9aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
