"""update users table

Revision ID: 227880440507
Revises: 17b6718c03f5
Create Date: 2019-01-11 21:15:52.422352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227880440507'
down_revision = '17b6718c03f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
