"""add new tables: user_followers, user_payment_details

Revision ID: 23c15e6375b7
Revises: 461f2f5123a7
Create Date: 2019-01-04 09:22:19.896820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c15e6375b7'
down_revision = '461f2f5123a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_followers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_payment_details',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('payment_type', sa.String(), nullable=True),
    sa.Column('mobile_network', sa.String(), nullable=True),
    sa.Column('mobile_number', sa.String(), nullable=True),
    sa.Column('card_type', sa.String(), nullable=True),
    sa.Column('card_number', sa.String(), nullable=True),
    sa.Column('card_expiration_date', sa.String(), nullable=True),
    sa.Column('card_verification_code', sa.String(), nullable=True),
    sa.Column('default_payment', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_payment_details_payment_type'), 'user_payment_details', ['payment_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_payment_details_payment_type'), table_name='user_payment_details')
    op.drop_table('user_payment_details')
    op.drop_table('user_followers')
    # ### end Alembic commands ###
