"""empty message

Revision ID: 2491895b43dc
Revises: fe40996ff5e6
Create Date: 2020-02-08 13:59:18.431920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2491895b43dc'
down_revision = 'fe40996ff5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_categories', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_categories', 'slug')
    # ### end Alembic commands ###
