"""add new table: app_notifications

Revision ID: 24eab0726b14
Revises: d9d2103d2cfb
Create Date: 2019-03-29 10:47:29.752990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24eab0726b14'
down_revision = 'd9d2103d2cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('recipient_id', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_notifications_notification_type'), 'app_notifications', ['notification_type'], unique=False)
    op.drop_index('ix_user_notifications_due_post_id', table_name='user_notifications')
    op.drop_index('ix_user_notifications_follower_id', table_name='user_notifications')
    op.drop_index('ix_user_notifications_new_event_id', table_name='user_notifications')
    op.drop_index('ix_user_notifications_type', table_name='user_notifications')
    op.drop_table('user_notifications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notifications',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('follower_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('new_event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('due_post_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['due_post_id'], ['events.id'], name='user_notifications_due_post_id_fkey'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='user_notifications_follower_id_fkey'),
    sa.ForeignKeyConstraint(['new_event_id'], ['events.id'], name='user_notifications_new_event_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_notifications_pkey')
    )
    op.create_index('ix_user_notifications_type', 'user_notifications', ['type'], unique=False)
    op.create_index('ix_user_notifications_new_event_id', 'user_notifications', ['new_event_id'], unique=False)
    op.create_index('ix_user_notifications_follower_id', 'user_notifications', ['follower_id'], unique=False)
    op.create_index('ix_user_notifications_due_post_id', 'user_notifications', ['due_post_id'], unique=False)
    op.drop_index(op.f('ix_app_notifications_notification_type'), table_name='app_notifications')
    op.drop_table('app_notifications')
    # ### end Alembic commands ###
