"""update ticket reservations table

Revision ID: 26ad363cbda9
Revises: 9309968b66e5
Create Date: 2019-03-21 16:47:51.287563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26ad363cbda9'
down_revision = '9309968b66e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ticket_reservations_ticket_type_id_reservation_by_id_key', 'ticket_reservations', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ticket_reservations_ticket_type_id_reservation_by_id_key', 'ticket_reservations', ['ticket_type_id', 'reservation_by_id'])
    # ### end Alembic commands ###
