"""update user payment table

Revision ID: 31fbdd250398
Revises: 0fcde15db3ab
Create Date: 2019-05-18 21:14:13.034948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31fbdd250398'
down_revision = '0fcde15db3ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_payment_details', sa.Column('card_cv', sa.String(), nullable=True))
    op.add_column('user_payment_details', sa.Column('card_name', sa.String(), nullable=True))
    op.drop_column('user_payment_details', 'card_verification_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_payment_details', sa.Column('card_verification_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_payment_details', 'card_name')
    op.drop_column('user_payment_details', 'card_cv')
    # ### end Alembic commands ###
