"""update eventmedia

Revision ID: 38e697622418
Revises: 9e3f6d8a271b
Create Date: 2019-05-31 17:45:27.988144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e697622418'
down_revision = '9e3f6d8a271b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
