"""create new tables

Revision ID: 3b84e6c30a30
Revises: 227880440507
Create Date: 2019-01-14 20:17:53.576294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b84e6c30a30'
down_revision = '227880440507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_login_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('login_at', sa.DateTime(), nullable=True),
    sa.Column('logout_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_location', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_login_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_login_sessions_session_token'), 'user_login_sessions', ['session_token'], unique=False)
    op.create_table('user_notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('follower_id', sa.String(), nullable=True),
    sa.Column('new_event_id', sa.String(), nullable=True),
    sa.Column('due_post_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['due_post_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['new_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notifications_due_post_id'), 'user_notifications', ['due_post_id'], unique=False)
    op.create_index(op.f('ix_user_notifications_follower_id'), 'user_notifications', ['follower_id'], unique=False)
    op.create_index(op.f('ix_user_notifications_new_event_id'), 'user_notifications', ['new_event_id'], unique=False)
    op.create_index(op.f('ix_user_notifications_type'), 'user_notifications', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_notifications_type'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_new_event_id'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_follower_id'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_due_post_id'), table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index(op.f('ix_user_login_sessions_session_token'), table_name='user_login_sessions')
    op.drop_table('user_login_sessions')
    op.drop_table('user_login_history')
    # ### end Alembic commands ###
