"""create brand_validations table

Revision ID: 3c9fb7cb8285
Revises: 420fcd32351b
Create Date: 2018-12-14 22:04:17.300382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9fb7cb8285'
down_revision = '420fcd32351b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_validations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('validator_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('brand_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brand_validations')
    # ### end Alembic commands ###
