"""update table apps_notifications

Revision ID: 3e3681652db6
Revises: f4ffe38879d2
Create Date: 2019-03-29 15:49:28.482218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3681652db6'
down_revision = 'f4ffe38879d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
