"""update event media table

Revision ID: 41ac8bb53fd8
Revises: 042f01b0898b
Create Date: 2019-05-31 08:48:50.013647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ac8bb53fd8'
down_revision = '042f01b0898b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
