"""update event_tickets

Revision ID: 4415fde0584d
Revises: 54860ea98850
Create Date: 2019-03-26 21:02:23.943833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4415fde0584d'
down_revision = '54860ea98850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_tickets', 'is_ownership_by_assignment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_tickets', sa.Column('is_ownership_by_assignment', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
