"""update users table

Revision ID: 461f2f5123a7
Revises: fa926ef53fd7
Create Date: 2019-01-03 09:58:06.666051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461f2f5123a7'
down_revision = 'fa926ef53fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
