"""update table

Revision ID: 483f6066a4e6
Revises: 845b3a51b232
Create Date: 2019-03-25 16:52:01.773693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483f6066a4e6'
down_revision = '845b3a51b232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_tickets', sa.Column('owner_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'event_tickets', 'users', ['owner_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_tickets', type_='foreignkey')
    op.drop_column('event_tickets', 'owner_id')
    # ### end Alembic commands ###
