"""update discounts table

Revision ID: 4a18d3973afe
Revises: 75cf78d1fe93
Create Date: 2019-05-28 14:36:27.075342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a18d3973afe'
down_revision = '75cf78d1fe93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_ticket_discounts', sa.Column('type', sa.String(), nullable=True))
    op.drop_constraint('event_ticket_discounts_type_id_fkey', 'event_ticket_discounts', type_='foreignkey')
    op.drop_column('event_ticket_discounts', 'type_id')
    op.add_column('ticket_sale_lines', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.add_column('ticket_sale_lines', sa.Column('total_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_sale_lines', 'total_amount')
    op.drop_column('ticket_sale_lines', 'discount_amount')
    op.add_column('event_ticket_discounts', sa.Column('type_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('event_ticket_discounts_type_id_fkey', 'event_ticket_discounts', 'event_ticket_discount_types', ['type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('event_ticket_discounts', 'type')
    # ### end Alembic commands ###
