"""add event_id field to event_ticket_assignments table

Revision ID: 4a84d15b4844
Revises: 5a0f2ce5040d
Create Date: 2019-05-16 14:04:45.024697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a84d15b4844'
down_revision = '5a0f2ce5040d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_ticket_assignments', sa.Column('event_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'event_ticket_assignments', 'events', ['event_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_ticket_assignments', type_='foreignkey')
    op.drop_column('event_ticket_assignments', 'event_id')
    # ### end Alembic commands ###
