"""update ticketing tables

Revision ID: 4c68ac8f3ed6
Revises: 93a70c8ea8ff
Create Date: 2019-03-25 12:20:52.301290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c68ac8f3ed6'
down_revision = '93a70c8ea8ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_tickets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('sale_line_id', sa.String(), nullable=True),
    sa.Column('sale_order_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_line_id'], ['ticket_sale_lines.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_order_id'], ['ticket_sales.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('event_ticket_assignments_event_id_fkey', 'event_ticket_assignments', type_='foreignkey')
    op.drop_column('event_ticket_assignments', 'entrance_code')
    op.drop_column('event_ticket_assignments', 'event_id')
    op.add_column('ticket_sale_lines', sa.Column('sale_order_id', sa.String(), nullable=True))
    op.add_column('ticket_sale_lines', sa.Column('ticket_qty', sa.Integer(), nullable=True))
    op.drop_constraint('ticket_sale_lines_sale_id_fkey', 'ticket_sale_lines', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_sale_lines', 'ticket_sales', ['sale_order_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ticket_sale_lines', 'ref')
    op.drop_column('ticket_sale_lines', 'sale_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_sale_lines', sa.Column('sale_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ticket_sale_lines', sa.Column('ref', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ticket_sale_lines', type_='foreignkey')
    op.create_foreign_key('ticket_sale_lines_sale_id_fkey', 'ticket_sale_lines', 'ticket_sales', ['sale_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ticket_sale_lines', 'ticket_qty')
    op.drop_column('ticket_sale_lines', 'sale_order_id')
    op.add_column('event_ticket_assignments', sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_ticket_assignments', sa.Column('entrance_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('event_ticket_assignments_event_id_fkey', 'event_ticket_assignments', 'events', ['event_id'], ['id'])
    op.drop_table('event_tickets')
    # ### end Alembic commands ###
