"""empty message

Revision ID: 4f0054b7b153
Revises: c7921a4c1355
Create Date: 2019-12-31 08:49:44.190495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0054b7b153'
down_revision = 'c7921a4c1355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
