"""update brand_validations table

Revision ID: 4faf1a4d278d
Revises: 8538144f35e4
Create Date: 2018-12-24 20:51:18.151894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4faf1a4d278d'
down_revision = '8538144f35e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
