"""update user payment table

Revision ID: 52c4f435bc3d
Revises: 31fbdd250398
Create Date: 2019-05-18 21:27:21.471637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c4f435bc3d'
down_revision = '31fbdd250398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
