"""update event_tikets tables

Revision ID: 54860ea98850
Revises: 07cb96c90f4c
Create Date: 2019-03-26 21:01:27.977489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54860ea98850'
down_revision = '07cb96c90f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_tickets', sa.Column('is_ownership_by_assignment', sa.Boolean(), nullable=True))
    op.drop_column('event_tickets', 'my_assignment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_tickets', sa.Column('my_assignment', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('event_tickets', 'is_ownership_by_assignment')
    # ### end Alembic commands ###
