"""update event_sponsors table

Revision ID: 57e34a13ebbf
Revises: 62407377b5ff
Create Date: 2018-12-15 08:14:10.639044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e34a13ebbf'
down_revision = '62407377b5ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
