"""update event media

Revision ID: 57ee6641bc2c
Revises: 87a661748b9a
Create Date: 2019-06-02 08:47:07.146178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ee6641bc2c'
down_revision = '87a661748b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_media', 'is_poster')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_media', sa.Column('is_poster', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
