"""update event_ticket.qty field

Revision ID: 5a0f2ce5040d
Revises: ae376d475171
Create Date: 2019-05-10 15:48:57.774432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0f2ce5040d'
down_revision = 'ae376d475171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
