"""updated

Revision ID: 5d0d66417739
Revises: 4c68ac8f3ed6
Create Date: 2019-03-25 12:34:02.515722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d0d66417739'
down_revision = '4c68ac8f3ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
