"""empty message

Revision ID: 5d4f1d63e410
Revises: 93b8b37ed10a
Create Date: 2020-02-08 14:04:51.264525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4f1d63e410'
down_revision = '93b8b37ed10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
