"""update user_payment_details

Revision ID: 5e90242c6ddf
Revises: b83bf0d03b03
Create Date: 2019-01-04 09:55:46.696960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e90242c6ddf'
down_revision = 'b83bf0d03b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_payment_details', sa.Column('default_payment_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_payment_details_default_payment_type'), 'user_payment_details', ['default_payment_type'], unique=False)
    op.drop_index('ix_user_payment_details_payment_type', table_name='user_payment_details')
    op.drop_column('user_payment_details', 'payment_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_payment_details', sa.Column('payment_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_user_payment_details_payment_type', 'user_payment_details', ['payment_type'], unique=False)
    op.drop_index(op.f('ix_user_payment_details_default_payment_type'), table_name='user_payment_details')
    op.drop_column('user_payment_details', 'default_payment_type')
    # ### end Alembic commands ###
