"""empty message

Revision ID: 5ebeb197728a
Revises: d132bc6fd778
Create Date: 2020-01-03 11:47:51.731535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ebeb197728a'
down_revision = 'd132bc6fd778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
