"""update event_sponsors table

Revision ID: 62407377b5ff
Revises: b5e94155e96e
Create Date: 2018-12-15 08:13:53.056543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62407377b5ff'
down_revision = 'b5e94155e96e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
