"""update eventmedia

Revision ID: 633c0f8a4688
Revises: ecdd79aa7a7a
Create Date: 2019-05-31 17:48:26.446711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633c0f8a4688'
down_revision = 'ecdd79aa7a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_media', 'cover_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_media', sa.Column('cover_image', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
