"""update tables

Revision ID: 74d87a047847
Revises: 9baf4cd00dc0
Create Date: 2019-03-20 08:37:32.014811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d87a047847'
down_revision = '9baf4cd00dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_reservations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_type_id', sa.String(), nullable=True),
    sa.Column('ticket_qty', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('reserved_by_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['reserved_by_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['event_ticket_types.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_reservations_created_at'), 'ticket_reservations', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticket_reservations_ticket_type_id'), 'ticket_reservations', ['ticket_type_id'], unique=False)
    op.create_index(op.f('ix_ticket_reservations_updated_at'), 'ticket_reservations', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_reservations_updated_at'), table_name='ticket_reservations')
    op.drop_index(op.f('ix_ticket_reservations_ticket_type_id'), table_name='ticket_reservations')
    op.drop_index(op.f('ix_ticket_reservations_created_at'), table_name='ticket_reservations')
    op.drop_table('ticket_reservations')
    # ### end Alembic commands ###
