"""update event_tickets table

Revision ID: 75cf78d1fe93
Revises: 4d67c96175cb
Create Date: 2019-05-25 18:56:28.708262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75cf78d1fe93'
down_revision = '4d67c96175cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_tickets', sa.Column('ticket_type_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'event_tickets', 'event_ticket_types', ['ticket_type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_tickets', type_='foreignkey')
    op.drop_column('event_tickets', 'ticket_type_id')
    # ### end Alembic commands ###
