"""update users

Revision ID: 78bb32d9fb63
Revises: 88a75f0dd226
Create Date: 2019-01-10 20:58:03.331857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78bb32d9fb63'
down_revision = '88a75f0dd226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
