"""payment details

Revision ID: 79612372eb17
Revises: 4a84d15b4844
Create Date: 2019-05-18 12:09:39.145707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79612372eb17'
down_revision = '4a84d15b4844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_payment_details', sa.Column('is_default_payment', sa.Boolean(), nullable=True))
    op.add_column('user_payment_details', sa.Column('type', sa.String(), nullable=True))
    op.drop_column('user_payment_details', 'default_payment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_payment_details', sa.Column('default_payment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_payment_details', 'type')
    op.drop_column('user_payment_details', 'is_default_payment')
    # ### end Alembic commands ###
