"""create new tables

Revision ID: 7cf78cccc4ca
Revises: 3b84e6c30a30
Create Date: 2019-01-14 20:45:33.794050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf78cccc4ca'
down_revision = '3b84e6c30a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_notifications', sa.Column('is_read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_notifications', 'is_read')
    # ### end Alembic commands ###
