"""update event_tickets

Revision ID: 80374c8bd877
Revises: 4415fde0584d
Create Date: 2019-03-26 21:02:43.786111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80374c8bd877'
down_revision = '4415fde0584d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_tickets', sa.Column('is_assigned_ticket', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_tickets', 'is_assigned_ticket')
    # ### end Alembic commands ###
