"""update tables

Revision ID: 845b3a51b232
Revises: ded2c535f98c
Create Date: 2019-03-25 14:56:31.600061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845b3a51b232'
down_revision = 'ded2c535f98c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
