"""update event_sponsors table

Revision ID: 8538144f35e4
Revises: 57e34a13ebbf
Create Date: 2018-12-15 08:15:18.682288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8538144f35e4'
down_revision = '57e34a13ebbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_sponsors_email', table_name='event_sponsors')
    op.drop_index('ix_event_sponsors_phone_number', table_name='event_sponsors')
    op.drop_column('event_sponsors', 'phone_number')
    op.drop_column('event_sponsors', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_sponsors', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_sponsors', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_event_sponsors_phone_number', 'event_sponsors', ['phone_number'], unique=False)
    op.create_index('ix_event_sponsors_email', 'event_sponsors', ['email'], unique=False)
    # ### end Alembic commands ###
