"""update eventmedia

Revision ID: 8711e968e4b6
Revises: 633c0f8a4688
Create Date: 2019-05-31 17:48:52.992212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8711e968e4b6'
down_revision = '633c0f8a4688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_media', sa.Column('is_poster', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_media', 'is_poster')
    # ### end Alembic commands ###
