"""update event media

Revision ID: 87a661748b9a
Revises: 940bbfba861b
Create Date: 2019-06-01 23:38:54.988876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a661748b9a'
down_revision = '940bbfba861b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
