"""update users

Revision ID: 88a75f0dd226
Revises: 0da5ff49b9d8
Create Date: 2019-01-10 20:21:36.496597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a75f0dd226'
down_revision = '0da5ff49b9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
