"""update tables again

Revision ID: 8bee16681d88
Revises: 74d87a047847
Create Date: 2019-03-20 08:41:08.506362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bee16681d88'
down_revision = '74d87a047847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_reservations', sa.Column('reservation_by_id', sa.String(), nullable=True))
    op.drop_constraint('ticket_reservations_reserved_by_id_fkey', 'ticket_reservations', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_reservations', 'users', ['reservation_by_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ticket_reservations', 'reserved_by_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_reservations', sa.Column('reserved_by_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ticket_reservations', type_='foreignkey')
    op.create_foreign_key('ticket_reservations_reserved_by_id_fkey', 'ticket_reservations', 'users', ['reserved_by_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ticket_reservations', 'reservation_by_id')
    # ### end Alembic commands ###
