"""add ref field to ticket_sales

Revision ID: 9059bc9d224f
Revises: ac39124282d9
Create Date: 2019-05-29 10:43:21.216298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9059bc9d224f'
down_revision = 'ac39124282d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_sales', sa.Column('ref', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_sales', 'ref')
    # ### end Alembic commands ###
