"""update sale lines

Revision ID: 918a13c40572
Revises: 8711e968e4b6
Create Date: 2019-06-01 23:34:39.535250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918a13c40572'
down_revision = '8711e968e4b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_media', 'is_poster')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_media', sa.Column('is_poster', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
