"""update user payment table

Revision ID: 91a32166c4fd
Revises: 52c4f435bc3d
Create Date: 2019-05-18 21:31:30.995980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a32166c4fd'
down_revision = '52c4f435bc3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
