"""update reservations table

Revision ID: 9309968b66e5
Revises: cb6a271bc83b
Create Date: 2019-03-21 16:33:23.121404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9309968b66e5'
down_revision = 'cb6a271bc83b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_reservations', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_ticket_reservations_expires_at'), 'ticket_reservations', ['expires_at'], unique=False)
    op.drop_index('ix_ticket_reservations_updated_at', table_name='ticket_reservations')
    op.create_unique_constraint(None, 'ticket_reservations', ['ticket_type_id', 'reservation_by_id'])
    op.drop_column('ticket_reservations', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_reservations', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ticket_reservations', type_='unique')
    op.create_index('ix_ticket_reservations_updated_at', 'ticket_reservations', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_ticket_reservations_expires_at'), table_name='ticket_reservations')
    op.drop_column('ticket_reservations', 'expires_at')
    # ### end Alembic commands ###
