"""update reservation table

Revision ID: 93a70c8ea8ff
Revises: bcf1e576218e
Create Date: 2019-03-22 19:14:44.628175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a70c8ea8ff'
down_revision = 'bcf1e576218e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_reservations', sa.Column('total_tickets_qty', sa.Integer(), nullable=True))
    op.drop_column('ticket_reservations', 'total_ticktets_qty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_reservations', sa.Column('total_ticktets_qty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('ticket_reservations', 'total_tickets_qty')
    # ### end Alembic commands ###
