"""update event media

Revision ID: 940bbfba861b
Revises: 918a13c40572
Create Date: 2019-06-01 23:35:56.866424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940bbfba861b'
down_revision = '918a13c40572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
