"""update event_organizers table

Revision ID: 9494429cb673
Revises: c6515edb8c57
Create Date: 2019-02-05 20:19:03.849554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9494429cb673'
down_revision = 'c6515edb8c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_organizers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('event_organizers', 'email')
    op.drop_column('event_organizers', 'name')
    op.drop_column('event_organizers', 'upated_at')
    op.drop_column('event_organizers', 'is_not_user')
    op.drop_column('event_organizers', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_organizers', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_organizers', sa.Column('is_not_user', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('event_organizers', sa.Column('upated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('event_organizers', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_organizers', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('event_organizers', 'updated_at')
    # ### end Alembic commands ###
