"""update media tables

Revision ID: 9631284ddb87
Revises: c6f58a90cafe
Create Date: 2019-06-03 18:17:08.575194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9631284ddb87'
down_revision = 'c6f58a90cafe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_review_comment_media', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('event_review_comment_media', sa.Column('filename', sa.String(), nullable=True))
    op.add_column('event_review_comment_media', sa.Column('media_type', sa.String(), nullable=True))
    op.add_column('event_review_comment_media', sa.Column('poster', sa.Boolean(), nullable=True))
    op.add_column('event_review_comment_media', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column('event_review_comment_media', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_event_review_comment_media_type', table_name='event_review_comment_media')
    op.drop_column('event_review_comment_media', 'url')
    op.drop_column('event_review_comment_media', 'type')
    op.add_column('event_review_comment_responses_media', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('event_review_comment_responses_media', sa.Column('filename', sa.String(), nullable=True))
    op.add_column('event_review_comment_responses_media', sa.Column('media_type', sa.String(), nullable=True))
    op.add_column('event_review_comment_responses_media', sa.Column('poster', sa.Boolean(), nullable=True))
    op.add_column('event_review_comment_responses_media', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column('event_review_comment_responses_media', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_event_review_comment_responses_media_type', table_name='event_review_comment_responses_media')
    op.drop_column('event_review_comment_responses_media', 'url')
    op.drop_column('event_review_comment_responses_media', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_review_comment_responses_media', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_review_comment_responses_media', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_event_review_comment_responses_media_type', 'event_review_comment_responses_media', ['type'], unique=False)
    op.drop_column('event_review_comment_responses_media', 'updated_at')
    op.drop_column('event_review_comment_responses_media', 'source_url')
    op.drop_column('event_review_comment_responses_media', 'poster')
    op.drop_column('event_review_comment_responses_media', 'media_type')
    op.drop_column('event_review_comment_responses_media', 'filename')
    op.drop_column('event_review_comment_responses_media', 'created_at')
    op.add_column('event_review_comment_media', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_review_comment_media', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_event_review_comment_media_type', 'event_review_comment_media', ['type'], unique=False)
    op.drop_column('event_review_comment_media', 'updated_at')
    op.drop_column('event_review_comment_media', 'source_url')
    op.drop_column('event_review_comment_media', 'poster')
    op.drop_column('event_review_comment_media', 'media_type')
    op.drop_column('event_review_comment_media', 'filename')
    op.drop_column('event_review_comment_media', 'created_at')
    # ### end Alembic commands ###
