"""update event table

Revision ID: 9ad0e9d8925a
Revises: 4faf1a4d278d
Create Date: 2018-12-26 07:55:04.448840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad0e9d8925a'
down_revision = '4faf1a4d278d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_sales', sa.Column('customer_id', sa.String(), nullable=True))
    op.drop_constraint(u'ticket_sales_user_id_fkey', 'ticket_sales', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_sales', 'users', ['customer_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ticket_sales', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_sales', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ticket_sales', type_='foreignkey')
    op.create_foreign_key(u'ticket_sales_user_id_fkey', 'ticket_sales', 'users', ['user_id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.drop_column('ticket_sales', 'customer_id')
    # ### end Alembic commands ###
