"""update event media

Revision ID: 9ba9ff3f9f77
Revises: b5a655e968d5
Create Date: 2019-06-02 08:51:31.935868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba9ff3f9f77'
down_revision = 'b5a655e968d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_media', sa.Column('poster', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_media', 'poster')
    # ### end Alembic commands ###
