"""update EventAttendee table

Revision ID: 9baf4cd00dc0
Revises: bec605ee2588
Create Date: 2019-03-20 08:21:25.494013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9baf4cd00dc0'
down_revision = 'bec605ee2588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
