"""update event table

Revision ID: 9d63e411100e
Revises: 9ad0e9d8925a
Create Date: 2018-12-26 07:55:58.764160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d63e411100e'
down_revision = '9ad0e9d8925a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
