"""update eventmedia

Revision ID: 9e3f6d8a271b
Revises: 41ac8bb53fd8
Create Date: 2019-05-31 17:43:49.742527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3f6d8a271b'
down_revision = '41ac8bb53fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
