"""updated user payment details

Revision ID: a727f8e9e68c
Revises: f9b8b839d9b1
Create Date: 2019-05-18 19:47:48.197257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a727f8e9e68c'
down_revision = 'f9b8b839d9b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
