"""update sale lines

Revision ID: ac39124282d9
Revises: 1a3b59ce4473
Create Date: 2019-05-28 17:34:14.761295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac39124282d9'
down_revision = '1a3b59ce4473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
