"""add is_published to events table

Revision ID: ae376d475171
Revises: 1adbcdb8037a
Create Date: 2019-04-01 16:30:24.470981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae376d475171'
down_revision = '1adbcdb8037a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_events_is_published'), 'events', ['is_published'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_is_published'), table_name='events')
    op.drop_column('events', 'is_published')
    # ### end Alembic commands ###
