"""update users table

Revision ID: b16831cebfb1
Revises: 0d63c609ce6a
Create Date: 2019-01-11 15:59:51.343680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16831cebfb1'
down_revision = '0d63c609ce6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
