"""add created_at field to some tables

Revision ID: b4a1a439a177
Revises: e0b096f0adaa
Create Date: 2019-06-03 15:41:12.001606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a1a439a177'
down_revision = 'e0b096f0adaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_review_comment_responses', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('event_review_comments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('event_review_comments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('event_review_media', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('event_review_upvotes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('event_reviews', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('event_reviews', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_reviews', 'updated_at')
    op.drop_column('event_reviews', 'created_at')
    op.drop_column('event_review_upvotes', 'updated_at')
    op.drop_column('event_review_media', 'created_at')
    op.drop_column('event_review_comments', 'updated_at')
    op.drop_column('event_review_comments', 'created_at')
    op.drop_column('event_review_comment_responses', 'created_at')
    # ### end Alembic commands ###
