"""update event media

Revision ID: b5a655e968d5
Revises: 57ee6641bc2c
Create Date: 2019-06-02 08:50:15.767206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a655e968d5'
down_revision = '57ee6641bc2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
