"""update followers tabale

Revision ID: b83bf0d03b03
Revises: 17bfddb4bdc5
Create Date: 2019-01-04 09:43:34.231068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83bf0d03b03'
down_revision = '17bfddb4bdc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'user_followers_follower_id_fkey', 'user_followers', type_='foreignkey')
    op.create_foreign_key(None, 'user_followers', 'users', ['follower_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_followers', type_='foreignkey')
    op.create_foreign_key(u'user_followers_follower_id_fkey', 'user_followers', 'users', ['follower_id'], ['id'])
    # ### end Alembic commands ###
