"""update a lot of tables

Revision ID: bcf1e576218e
Revises: edca11826acb
Create Date: 2019-03-22 19:01:04.281490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf1e576218e'
down_revision = 'edca11826acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_reservations', sa.Column('total_ticktets_qty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_reservations', 'total_ticktets_qty')
    # ### end Alembic commands ###
