"""update users table

Revision ID: c6515edb8c57
Revises: e9c16189964a
Create Date: 2019-02-03 08:13:17.061878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6515edb8c57'
down_revision = 'e9c16189964a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
