"""empty message

Revision ID: c6d16a175b84
Revises: ac2c33efdf9a
Create Date: 2020-02-08 13:55:20.267079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d16a175b84'
down_revision = 'ac2c33efdf9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
