"""add created_at field to some tables

Revision ID: c6f58a90cafe
Revises: b4a1a439a177
Create Date: 2019-06-03 18:11:55.423355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f58a90cafe'
down_revision = 'b4a1a439a177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_review_media', sa.Column('filename', sa.String(), nullable=True))
    op.add_column('event_review_media', sa.Column('media_type', sa.String(), nullable=True))
    op.add_column('event_review_media', sa.Column('poster', sa.Boolean(), nullable=True))
    op.add_column('event_review_media', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column('event_review_media', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_event_review_media_type', table_name='event_review_media')
    op.drop_column('event_review_media', 'url')
    op.drop_column('event_review_media', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_review_media', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_review_media', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_event_review_media_type', 'event_review_media', ['type'], unique=False)
    op.drop_column('event_review_media', 'updated_at')
    op.drop_column('event_review_media', 'source_url')
    op.drop_column('event_review_media', 'poster')
    op.drop_column('event_review_media', 'media_type')
    op.drop_column('event_review_media', 'filename')
    # ### end Alembic commands ###
