"""empty message

Revision ID: c7921a4c1355
Revises: 8eea75ffaabe
Create Date: 2019-12-30 22:53:20.195845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7921a4c1355'
down_revision = '8eea75ffaabe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_media', sa.Column('format', sa.String(), nullable=True))
    op.drop_column('brand_media', 'poster')
    op.drop_column('brand_media', 'media_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_media', sa.Column('media_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('brand_media', sa.Column('poster', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('brand_media', 'format')
    # ### end Alembic commands ###
