"""update tables once again

Revision ID: cb6a271bc83b
Revises: 8bee16681d88
Create Date: 2019-03-20 09:59:56.288324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb6a271bc83b'
down_revision = '8bee16681d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
