"""add reservation_lines table

Revision ID: cbcbd42aa63d
Revises: 062c67821f70
Create Date: 2019-03-22 16:55:13.442159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbcbd42aa63d'
down_revision = '062c67821f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
