"""update eventmedia

Revision ID: ce95952517bd
Revises: 1b08b1a105da
Create Date: 2019-05-31 17:46:59.731354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce95952517bd'
down_revision = '1b08b1a105da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
