"""empty message

Revision ID: d05851a05863
Revises: 3ca0846e0de2
Create Date: 2019-12-30 12:57:22.305301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05851a05863'
down_revision = '3ca0846e0de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
