"""empty message

Revision ID: d132bc6fd778
Revises: 4f0054b7b153
Create Date: 2020-01-03 09:16:33.433393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd132bc6fd778'
down_revision = '4f0054b7b153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('foundedDate', sa.String(), nullable=True))
    op.add_column('brands', sa.Column('founder', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'founder')
    op.drop_column('brands', 'foundedDate')
    # ### end Alembic commands ###
