"""update event_tickets

Revision ID: d9d2103d2cfb
Revises: 80374c8bd877
Create Date: 2019-03-26 21:03:21.735901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d2103d2cfb'
down_revision = '80374c8bd877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_tickets', 'is_assigned_ticket')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_tickets', sa.Column('is_assigned_ticket', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
