"""update tables

Revision ID: ded2c535f98c
Revises: a28268f81187
Create Date: 2019-03-25 14:55:28.323335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded2c535f98c'
down_revision = 'a28268f81187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
