"""add new table: sale_line_discount

Revision ID: e09c1a6f856e
Revises: fcff6fcd366f
Create Date: 2019-05-28 14:58:16.955336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e09c1a6f856e'
down_revision = 'fcff6fcd366f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_sale_lines_discounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('discount_type_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['discount_type_id'], ['event_ticket_discounts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_sale_lines_discounts')
    # ### end Alembic commands ###
