"""update event media

Revision ID: e0b096f0adaa
Revises: 9ba9ff3f9f77
Create Date: 2019-06-02 08:53:05.825908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b096f0adaa'
down_revision = '9ba9ff3f9f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
