"""update table

Revision ID: e76e2ed3f162
Revises: 14ec7f67cb83
Create Date: 2019-03-26 08:45:57.996536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76e2ed3f162'
down_revision = '14ec7f67cb83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
