"""update eventmedia

Revision ID: ecdd79aa7a7a
Revises: ce95952517bd
Create Date: 2019-05-31 17:47:59.478755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecdd79aa7a7a'
down_revision = 'ce95952517bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_media', sa.Column('cover_image', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_media', 'cover_image')
    # ### end Alembic commands ###
