"""add reservation_lines table

Revision ID: edca11826acb
Revises: cbcbd42aa63d
Create Date: 2019-03-22 16:56:38.057525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edca11826acb'
down_revision = 'cbcbd42aa63d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
