"""update user payment details table

Revision ID: f4c0bb94f7b5
Revises: 91a32166c4fd
Create Date: 2019-05-18 21:43:20.536209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c0bb94f7b5'
down_revision = '91a32166c4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
