"""update table apps_notifications

Revision ID: f4ffe38879d2
Revises: fc2c022abd6f
Create Date: 2019-03-29 15:41:36.226617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ffe38879d2'
down_revision = 'fc2c022abd6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_notifications', sa.Column('brand_id', sa.String(), nullable=True))
    op.add_column('app_notifications', sa.Column('event_id', sa.String(), nullable=True))
    op.add_column('app_notifications', sa.Column('ticket_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'app_notifications', 'brands', ['brand_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'app_notifications', 'events', ['event_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'app_notifications', 'event_tickets', ['ticket_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'app_notifications', type_='foreignkey')
    op.drop_constraint(None, 'app_notifications', type_='foreignkey')
    op.drop_constraint(None, 'app_notifications', type_='foreignkey')
    op.drop_column('app_notifications', 'ticket_id')
    op.drop_column('app_notifications', 'event_id')
    op.drop_column('app_notifications', 'brand_id')
    # ### end Alembic commands ###
