"""updated again

Revision ID: f6b4f93de9aa
Revises: 5d0d66417739
Create Date: 2019-03-25 12:37:27.499261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b4f93de9aa'
down_revision = '5d0d66417739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_ticket_assignments', sa.Column('ticket_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'event_ticket_assignments', 'event_tickets', ['ticket_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_ticket_assignments', type_='foreignkey')
    op.drop_column('event_ticket_assignments', 'ticket_id')
    # ### end Alembic commands ###
