"""updated

Revision ID: f9b8b839d9b1
Revises: 79612372eb17
Create Date: 2019-05-18 13:55:02.845095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b8b839d9b1'
down_revision = '79612372eb17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_payment_details', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user_payment_details', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_payment_details', 'updated_at')
    op.drop_column('user_payment_details', 'created_at')
    # ### end Alembic commands ###
