"""update event_ticket_assignments table

Revision ID: fa926ef53fd7
Revises: 1b7e7e20317c
Create Date: 2018-12-31 15:53:38.036210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa926ef53fd7'
down_revision = '1b7e7e20317c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_ticket_assignments', sa.Column('event_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'event_ticket_assignments', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_ticket_assignments', type_='foreignkey')
    op.drop_column('event_ticket_assignments', 'event_id')
    # ### end Alembic commands ###
