"""udpate app_notifications table

Revision ID: fc2c022abd6f
Revises: 24eab0726b14
Create Date: 2019-03-29 15:27:24.073065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc2c022abd6f'
down_revision = '24eab0726b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_notifications', sa.Column('actor_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'app_notifications', 'users', ['actor_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'app_notifications', type_='foreignkey')
    op.drop_column('app_notifications', 'actor_id')
    # ### end Alembic commands ###
