"""add fixed_amount to discounts table

Revision ID: fcff6fcd366f
Revises: 4a18d3973afe
Create Date: 2019-05-28 14:43:25.799672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcff6fcd366f'
down_revision = '4a18d3973afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_ticket_discounts', sa.Column('fixed_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_ticket_discounts', 'fixed_amount')
    # ### end Alembic commands ###
